version: '3.8'

services:
  app:
    image: agentkraft:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - HTTP_SERVER_LISTEN_ADDR=0.0.0.0
      - HTTP_SERVER_PORT=8080
      - YAML_CONFIG_FILE=/app/data/agents.yaml
      - REPO_TYPE=yamlconfig
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./examples:/app/data/
